annotate with @deprecated RPC methods that are only kept for SDK6 com…
decentraland/protocol pull request #107
Opened 2023-01-31 18:32 UTC by menduz

…patibility

2023-01-31 18:46 UTC, gonpombo8 reviewed
this `@deprecated` methods are going to still be visible to the content-creators ?
Like `import { } from '~system/SocialController' `
Because we are already not exposing some of the API's. 
https://github.com/decentraland/js-sdk-toolchain/blob/main/scripts/rpc-api-generation/index.ts#L34-L41

2023-02-01 12:29 UTC, nearnshaw requested changes

2023-02-01 12:29 UTC, nearnshaw commented on proto/decentraland/kernel/apis/players.proto
> +    // @deprecated, only available for SDK6 compatibility
// Returns data about a specific player, by id
// NOTE: To be deprecated after implementing foreign-entities and once the avatar scene uses SDK7

2023-02-01 12:29 UTC, nearnshaw commented on proto/decentraland/kernel/apis/players.proto
> +    // @deprecated, only available for SDK6 compatibility
// Returns a list of all the ids of players who are currently standing within the parcels of the scene
// NOTE: To be deprecated after implementing foreign-entities and once the avatar scene uses SDK7

2023-02-01 12:29 UTC, nearnshaw commented on proto/decentraland/kernel/apis/players.proto
> +    // @deprecated, only available for SDK6 compatibility
// Returns a list of all the ids of players who are currently connected to the same server and grouped together
// NOTE: To be deprecated after implementing foreign-entities and once the avatar scene uses SDK7

2023-02-03 14:39 UTC, menduz commented on proto/decentraland/kernel/apis/players.proto
> +    // @deprecated, only available for SDK6 compatibility
```suggestion
    // Returns a list of all the ids of players who are currently connected to the same server and grouped together
    // NOTE: To be deprecated after implementing foreign-entities and once the avatar scene uses SDK7
```

2023-02-03 14:39 UTC, menduz commented on proto/decentraland/kernel/apis/players.proto
> +    // @deprecated, only available for SDK6 compatibility
```suggestion
    // Returns a list of all the ids of players who are currently standing within the parcels of the scene
    // NOTE: To be deprecated after implementing foreign-entities and once the avatar scene uses SDK7
```

2023-02-03 14:40 UTC, menduz commented on proto/decentraland/kernel/apis/players.proto
> +    // @deprecated, only available for SDK6 compatibility
```suggestion
    // Returns data about a specific player, by id
    // NOTE: To be deprecated after implementing foreign-entities and once the avatar scene uses SDK7
```

2023-02-03 14:42 UTC, menduz commented on proto/decentraland/kernel/apis/scene.proto
> +}
@gonpombo8 would you also add the baseUrl and the content mappings? These are part of every scene, available in the LoadableScene type of the explorer

https://github.com/decentraland/unity-renderer/blob/495c203d9b9e0c02cc6e4376deb92dc45ac7f54d/browser-interface/packages/shared/types.ts#L186

2023-02-03 15:38 UTC, gonpombo8 approved these changes

2023-02-03 15:38 UTC, merged