chore: texture mapping movement polish
decentraland/protocol pull request #228
Opened 2024-10-31 19:18 UTC by AlejandroAlvarezMelucciDCL

Added documentation for new properties.

2024-11-07 13:50 UTC, kuruk-mm requested changes

2024-11-07 13:50 UTC, kuruk-mm commented on proto/decentraland/common/texture.proto
> +  // Offset for texture positioning.
can we add the formula of the final uv?
```
final uv = offset + (input uv * scale)
```

2024-11-07 14:41 UTC, AlejandroAlvarezMelucciDCL commented on proto/decentraland/common/texture.proto
> +  // Offset for texture positioning.
Sure thing!

2024-11-11 14:26 UTC, kuruk-mm approved these changes

2024-11-11 14:29 UTC, leanmendoza approved these changes

2024-11-11 14:30 UTC, merged