feat: avatar texture
decentraland/protocol pull request #63
Opened 2022-10-11 14:41 UTC by pravusjif

added avatar texture option in Material component

2022-10-17 19:28 UTC, leanmendoza submitted a review, later dismissed
LGTM! Before the release of ECS7, we can evaluate if the `albedoTexture` field should be a deeper one as `albedoTexture.avatarTexture` and `albedoTexture.texture` or keep this approach with a root exposing of the `oneof` (like it already has the MeshRenderer/MeshCollider).

2022-10-19 18:31 UTC, menduz requested changes

2022-10-19 19:01 UTC, menduz commented
Cross posting from https://github.com/decentraland/unity-renderer/pull/3235#discussion_r999832792

---

Here are references to this `oneof` occurrence
- https://github.com/decentraland/protocol/blob/main/proto/decentraland/sdk/components/mesh_renderer.proto#L24-L29

To map this to a concept, ideally we have a single `oneof` for each interface like this


```proto
message ITexture {
  oneof tex {
    ImageTexture image = 1;
    AvatarTexture avatar = 2;
    GltfTexture avatar = 3;
    // ResourceManagerTexture from_resource = 4;
  }
}

message Material {
  ITexture albedo_texture = 1;
  ITexture alpha_texture = 2;
}
```

And then in the implementation, the component decides how to get the specific (real) resource based on the union type like this

```ts

function getResourceFromTexture(protoTexture: PB.ITexture) {
  switch (......)
}

function updateMaterial(materialModel) {
  realMaterial.texture = getResourceFromTexture(materialModel.albedoTexture)
  realMaterial.alphaTexture = getResourceFromTexture(materialModel.alphaTexture)
}
```

That is extremely important to enable protocol extensibility and new kinds of textures. We can see clearly that once we need VideoTexture, it can be added to the `oneof`

```diff
 message ITexture {
   oneof tex {
     ImageTexture image = 1;
     AvatarTexture avatar = 2;
     GltfTexture avatar = 3;
+    VideoTexture video = 4;
   }
 }
```

2022-10-20 20:02 UTC, menduz commented on proto/decentraland/common/texture.proto
> +      SRCTexture src_texture = 1; // default = null
```suggestion
      SrcTexture src_texture = 1; // default = null
```

2022-10-20 20:02 UTC, menduz commented on proto/decentraland/sdk/components/material.proto
> +  optional decentraland.common.SRCTexture bump_texture = 6; // default = null
```suggestion
  optional decentraland.common.Texture alpha_texture = 4; // default = null
  optional decentraland.common.Texture emissive_texture = 5; // default = null
  optional decentraland.common.Texture bump_texture = 6; // default = null
```

2022-10-21 16:50 UTC, pravusjif commented
@menduz I implemented the requested changes.

Be aware that now the SDK nomenclature is a bit uglier:

```
  const mat = Material.create(entity, {
    texture: { 
      texture: {
        src: "images/scene-thumbnail.png"
      },
      avatarTexture: undefined
      
      // texture: undefined,
      // avatarTexture: {
      //   userId: "0x51777c0b8DBA8B4dfE8a1c3d0a1eDAA5B139B4e0" 
      // }
    }
  })
```

2022-10-21 21:20 UTC, menduz requested changes

2022-10-21 21:20 UTC, menduz commented on proto/decentraland/sdk/components/material.proto
> +  optional decentraland.common.Texture bump_texture = 6; // default = null
This three should also be TextureUnion to enable extensibility

2022-10-25 20:33 UTC, menduz approved these changes

2022-10-26 12:08 UTC, merged